"""Auditable runtime primitives for long-running coding agents."""

from contextopt.runtime.context import (
    CONTEXT_COMPILER_VERSION,
    MIN_TOOL_OUTPUT_TOKENS,
    CompiledContext,
    ContextBlockAnnotation,
    ContextBlockReceipt,
    ContextBudgetError,
    ContextCompiler,
    ContextCompilerConfig,
    ContextReceipt,
    compile_runtime_context,
    estimate_message_tokens,
    estimate_messages_tokens,
    estimate_text_tokens,
)
from contextopt.runtime.events import (
    EventLog,
    EventScan,
    RunLease,
    read_events,
    render_trace,
    render_trace_html,
    scan_events,
)
from contextopt.runtime.knowledge import (
    KNOWLEDGE_CHUNK_TAG,
    KNOWLEDGE_INDEX_SCHEMA_VERSION,
    KnowledgeIndexConfig,
    KnowledgeIndexReport,
    index_workspace,
    render_knowledge_index_console,
    render_knowledge_index_markdown,
)
from contextopt.runtime.memory import EvidenceRecord, MemorySnapshot
from contextopt.runtime.model import OpenAICompatibleModel, ScriptedModel
from contextopt.runtime.protocol import (
    AgentMessage,
    AgentRunResult,
    ModelClient,
    ModelRequest,
    ModelResponse,
    RunLimits,
    RunPermissions,
    TokenUsage,
    ToolCall,
    ToolDefinition,
    ToolOutcome,
)
from contextopt.runtime.recovery import (
    RecoveryError,
    RunProjection,
    replay_events,
    replay_events_with_checkpoint,
)
from contextopt.runtime.runner import AgentRunner, PendingToolResolution
from contextopt.runtime.semantic_memory import (
    SEMANTIC_MEMORY_SCHEMA_VERSION,
    MemoryFeedbackLabel,
    MemoryFeedbackResult,
    MemoryKind,
    MemoryStatus,
    MemoryWriteResult,
    SemanticMemoryEntry,
    SemanticMemoryMatch,
    SemanticMemoryStore,
)
from contextopt.runtime.tool_state import ToolExecutionPlan, ToolReconciliation
from contextopt.runtime.tools import WorkspaceTools
from contextopt.runtime.transcript import (
    MODEL_TRANSCRIPT_SCHEMA_VERSION,
    ModelTranscript,
    ModelTranscriptRecord,
    RecordingModel,
    ReplayModel,
    model_request_fingerprint,
)

__all__ = [
    "CONTEXT_COMPILER_VERSION",
    "KNOWLEDGE_CHUNK_TAG",
    "KNOWLEDGE_INDEX_SCHEMA_VERSION",
    "MIN_TOOL_OUTPUT_TOKENS",
    "MODEL_TRANSCRIPT_SCHEMA_VERSION",
    "SEMANTIC_MEMORY_SCHEMA_VERSION",
    "AgentMessage",
    "AgentRunResult",
    "AgentRunner",
    "CompiledContext",
    "ContextBlockAnnotation",
    "ContextBlockReceipt",
    "ContextBudgetError",
    "ContextCompiler",
    "ContextCompilerConfig",
    "ContextReceipt",
    "EventLog",
    "EventScan",
    "EvidenceRecord",
    "KnowledgeIndexConfig",
    "KnowledgeIndexReport",
    "MemoryFeedbackLabel",
    "MemoryFeedbackResult",
    "MemoryKind",
    "MemorySnapshot",
    "MemoryStatus",
    "MemoryWriteResult",
    "ModelClient",
    "ModelRequest",
    "ModelResponse",
    "ModelTranscript",
    "ModelTranscriptRecord",
    "OpenAICompatibleModel",
    "PendingToolResolution",
    "RecordingModel",
    "RecoveryError",
    "ReplayModel",
    "RunLease",
    "RunLimits",
    "RunPermissions",
    "RunProjection",
    "ScriptedModel",
    "SemanticMemoryEntry",
    "SemanticMemoryMatch",
    "SemanticMemoryStore",
    "TokenUsage",
    "ToolCall",
    "ToolDefinition",
    "ToolExecutionPlan",
    "ToolOutcome",
    "ToolReconciliation",
    "WorkspaceTools",
    "compile_runtime_context",
    "estimate_message_tokens",
    "estimate_messages_tokens",
    "estimate_text_tokens",
    "index_workspace",
    "model_request_fingerprint",
    "read_events",
    "render_knowledge_index_console",
    "render_knowledge_index_markdown",
    "render_trace",
    "render_trace_html",
    "replay_events",
    "replay_events_with_checkpoint",
    "scan_events",
]
