"""Auditable runtime primitives for long-running coding agents."""

from contextopt.runtime.context import (
    CONTEXT_COMPILER_VERSION,
    MIN_TOOL_OUTPUT_TOKENS,
    CompiledContext,
    ContextBlockAnnotation,
    ContextBlockReceipt,
    ContextBudgetError,
    ContextCompiler,
    ContextCompilerConfig,
    ContextReceipt,
    compile_runtime_context,
    estimate_message_tokens,
    estimate_messages_tokens,
    estimate_text_tokens,
)
from contextopt.runtime.events import (
    EventLog,
    EventScan,
    RunLease,
    read_events,
    render_trace,
    render_trace_html,
    scan_events,
)
from contextopt.runtime.memory import EvidenceRecord, MemorySnapshot
from contextopt.runtime.model import OpenAICompatibleModel, ScriptedModel
from contextopt.runtime.protocol import (
    AgentMessage,
    AgentRunResult,
    ModelClient,
    ModelRequest,
    ModelResponse,
    RunLimits,
    RunPermissions,
    TokenUsage,
    ToolCall,
    ToolDefinition,
    ToolOutcome,
)
from contextopt.runtime.recovery import (
    RecoveryError,
    RunProjection,
    replay_events,
    replay_events_with_checkpoint,
)
from contextopt.runtime.runner import AgentRunner, PendingToolResolution
from contextopt.runtime.semantic_memory import (
    SEMANTIC_MEMORY_SCHEMA_VERSION,
    MemoryKind,
    MemoryStatus,
    MemoryWriteResult,
    SemanticMemoryEntry,
    SemanticMemoryMatch,
    SemanticMemoryStore,
)
from contextopt.runtime.tool_state import ToolExecutionPlan, ToolReconciliation
from contextopt.runtime.tools import WorkspaceTools

__all__ = [
    "CONTEXT_COMPILER_VERSION",
    "MIN_TOOL_OUTPUT_TOKENS",
    "SEMANTIC_MEMORY_SCHEMA_VERSION",
    "AgentMessage",
    "AgentRunResult",
    "AgentRunner",
    "CompiledContext",
    "ContextBlockAnnotation",
    "ContextBlockReceipt",
    "ContextBudgetError",
    "ContextCompiler",
    "ContextCompilerConfig",
    "ContextReceipt",
    "EventLog",
    "EventScan",
    "EvidenceRecord",
    "MemoryKind",
    "MemorySnapshot",
    "MemoryStatus",
    "MemoryWriteResult",
    "ModelClient",
    "ModelRequest",
    "ModelResponse",
    "OpenAICompatibleModel",
    "PendingToolResolution",
    "RecoveryError",
    "RunLease",
    "RunLimits",
    "RunPermissions",
    "RunProjection",
    "ScriptedModel",
    "SemanticMemoryEntry",
    "SemanticMemoryMatch",
    "SemanticMemoryStore",
    "TokenUsage",
    "ToolCall",
    "ToolDefinition",
    "ToolExecutionPlan",
    "ToolOutcome",
    "ToolReconciliation",
    "WorkspaceTools",
    "compile_runtime_context",
    "estimate_message_tokens",
    "estimate_messages_tokens",
    "estimate_text_tokens",
    "read_events",
    "render_trace",
    "render_trace_html",
    "replay_events",
    "replay_events_with_checkpoint",
    "scan_events",
]
